### ISSUE TITLE
Extracting pod from a document

### ISSUE THREAD

**Issue by JJ** [finanalyst/pod-cached#7]
You have probably seen perl6/Pod-To-HTML#55, which is crucial for making pod6 be rendered in GitHub. As a prerequisite, we need a new way of obtaining the pod of a document without using eval. Do you think you could spin off CompUnit::PrecompilationRepository::Document for that and use it to simply cache and obtain the pod for a document?

**Comment by finanalyst** [comment]
JJ, I only just saw this message.
For some reason my email client is sending all github issues to spam. I have not figured out how to stop this.

**Comment by JJ** [comment]
No problem... You probably get a lot of those :-)

**Comment by JJ** [comment]
And anyway I eventually created Pod::Load. It has a fraction of the functionality of this one, but does the job.

**Comment by finanalyst** [comment]
closing issue as changes incorporated.
